version: 2.1
branch-defaults:
  master:
    environment: Elasticdemotimev16-env
global:
  application_name: demo-time-eb
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  sc: git